services:
  movies:
    image: vinaysteja0231/paymevics:latest
    ports:
      - "8080:8080"
    deploy:
      replicas: 2

  train:
    image: vinaysteja0231/paytrain:latest
    ports:
      - "8081:8081"
    deploy:
      replicas: 2

  dth:
    image: vinaysteja0231/paydth:latest
    ports:
      - "8082:8082"
    deploy:
      replicas: 2

  recharger:
    image: vinaysteja0231/payrecharge:latest
    ports:
      - "8083:8083"
    deploy:
      replicas: 2
