version: '3.8'
services:
  movies:
    image: vinaysteja/paymovies:latest
    ports:
      - "86:80"
    deploy:
      replicas: 3
  train:
    image: vinaysteja/paytrains:latest
    ports:
      - "87:80"
    deploy:
      replicas: 3
  dth:
    image: vinaysteja/paydth:latest
    ports:
      - "88:80"
    deploy:
      replicas: 3
  recharge:
    image: vinaysteja/payrecharge:latest
    ports:
      - "89:80"
    deploy:
      replicas: 3
