version: '3'
services:
  service-reg:
    image: vinaysteja0231/service-reg
    container_name: service-reg
    ports:
      - "8761:8761"  # Eureka service registry
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=default
    restart: always

  gateway:
    image: vinaysteja0231/gateway
    container_name: gateway
    ports:
      - "8090:8090"  # Gateway should expose its port to the public
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-reg:8761/eureka/
    depends_on:
      - service-reg
    restart: always

  user:
    image: vinaysteja0231/user
    container_name: user
    ports:
      - "8081:8081"
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-reg:8761/eureka/
    depends_on:
      - service-reg
    restart: always

  tour:
    image: vinaysteja0231/tour
    container_name: tour
    ports:
      - "8083:8083"
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-reg:8761/eureka/
    depends_on:
      - service-reg
    restart: always

  review:
    image: vinaysteja0231/review
    container_name: review
    ports:
      - "8085:8085"
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-reg:8761/eureka/
    depends_on:
      - service-reg
    restart: always

  touristguide:
    image: vinaysteja0231/touristguide
    container_name: touristguide
    ports:
      - "8088:8088"
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-reg:8761/eureka/
    depends_on:
      - service-reg
    restart: always

  payment:
    image: vinaysteja0231/payment
    container_name: payment
    ports:
      - "8089:8089"
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-reg:8761/eureka/
    depends_on:
      - service-reg
    restart: always

  booking:
    image: vinaysteja0231/booking
    container_name: booking
    ports:
      - "8084:8084"
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-reg:8761/eureka/
    depends_on:
      - service-reg
    restart: always

networks:
  app-network:
    driver: bridges
