services:
  movies:
    image: vinaysteja0231/paymovies:latest
    ports:
      - "80:80"
    deploy:
      replicas: 2

  train:
    image: vinaysteja0231/paytrains:latest
    ports:
      - "81:81"
    deploy:
      replicas: 2

  dth:
    image: vinaysteja0231/paydth:latest
    ports:
      - "82:82"
    deploy:
      replicas: 2

  recharger:
    image: vinaysteja0231/payrecharge:latest
    ports:
      - "83:83"
    deploy:
      replicas: 2
